Feature/k8 1.25 support
dell/csi-powerstore pull request #155
Opened 2022-09-27 09:24 UTC by adarsh-dell

# Description
Kubernete 1.25v support for CSI-PowerStore

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Installed the driver on k8 1.25 setup and have created some PVCs and Pods. Creation and deletion of PV works fine.
- [x] Run Automation suite on k8 1.25 setup against driver and all suites runs fine.

2022-09-28 05:48 UTC, spriya-m requested changes
We will continue supporting 1.21 as MKE is still on 1.21. Can you please modify the check to allow 1.21?

2022-09-28 09:45 UTC, adarsh-dell commented
> We will continue supporting 1.21 as MKE is still on 1.21. Can you please modify the check to allow 1.21?

Done.

2022-09-28 09:45 UTC, AkshaySainiDell approved these changes

2022-09-28 09:49 UTC, suryagupta4 submitted a review, later dismissed

2022-09-28 10:43 UTC, satyakonduri approved these changes

2022-09-29 06:06 UTC, spriya-m submitted a review, later dismissed

2022-09-29 07:16 UTC, AkshaySainiDell approved these changes

2022-09-29 07:19 UTC, suryagupta4 approved these changes

2022-09-29 07:19 UTC, merged