Feature/resiliency
dell/csi-powerstore pull request #194
Opened 2023-01-06 05:47 UTC by adarsh-dell

# Description
CSI extension development for supporting resiliency

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/587|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran UT for different different scenario and it worked as per the expectation

2023-01-10 06:00 UTC, AkshaySainiDell requested changes
We missed registering podmon server. Call podmon.RegisterPodmonServer(server, s) in controller.RegisterAdditionalServers()

2023-01-23 08:38 UTC, AkshaySainiDell approved these changes

2023-01-23 08:55 UTC, adarsh-dell commented on pkg/controller/controller.go
> +func (s *Service) IsIOInProgress(ctx context.Context, volID string, arrayConfig *array.PowerStoreArray, protocol string) (err error) {
Thanks @AkshaySainiDell  As a next PR for code improvement, will take care of this.

2023-01-23 09:21 UTC, suryagupta4 approved these changes

2023-01-23 09:32 UTC, suryagupta4 approved these changes

2023-01-23 09:36 UTC, AkshaySainiDell approved these changes

2023-01-23 09:37 UTC, merged