Update offline bundle instructions from CSI to CSM Operator
dell/csi-powerstore pull request #295
Opened 2023-12-14 17:10 UTC by KerryKovacevic

# Description
Updated documentation for offline bundle installation from referencing CSI Operator to CSM Operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2023-12-14 17:18 UTC, shaynafinocchiaro approved these changes

2023-12-14 17:18 UTC, EvgenyUglov approved these changes

2023-12-14 17:18 UTC, shaynafinocchiaro commented
Can you create a github issue and link it here?

2023-12-15 04:13 UTC, shanmydell requested changes
![Uploading image.png…]()

2023-12-18 14:33 UTC, KerryKovacevic commented
@shanmydell Based on the comments left on my other driver PRs, I am assuming your request was meant to refer to "DRIVERNAME" in the script. I have updated that here and will update for the rest of the repos as well.

2023-12-19 12:28 UTC, shanmydell submitted a review, later dismissed

2023-12-19 12:45 UTC, delldubey approved these changes
lgtm

2023-12-19 14:50 UTC, PeresKereotubo submitted a review, later dismissed

2023-12-19 15:38 UTC, gallacher commented on dell-csi-helm-installer/csi-offline-bundle.md
> +The `csm-offline-bundle.sh` script can be used to create a package for offline installation of Dell CSI storage providers for deployment via the CSM Operator.
"... to create a package for **the** offline installation of ... "

2023-12-20 12:04 UTC, adarsh-dell approved these changes
LGTM.

2023-12-20 12:52 UTC, merged