go version bump-up
dell/csi-powerstore pull request #315
Opened 2024-02-21 10:13 UTC by nitesh3108

Updating go version to latest available i.e. => 1.22

2024-02-21 20:09 UTC, hoppea2 approved these changes

2024-02-21 20:12 UTC, AronAtDell approved these changes

2024-02-22 06:25 UTC, shanmydell commented
@nitesh3108 : 
![image](https://github.com/dell/csi-powerstore/assets/82038610/ced299cc-c754-408a-a084-75875d61a8ea)
Please fix the above issue

2024-02-22 06:26 UTC, shanmydell requested changes
Please fix the failures in check

2024-02-22 11:18 UTC, panigs7 approved these changes

2024-02-22 11:20 UTC, chimanjain commented
@shanmydell Test checks are passing now.

2024-02-22 11:20 UTC, chimanjain approved these changes

2024-02-22 17:47 UTC, gallacher approved these changes

2024-02-23 06:34 UTC, AkshaySainiDell approved these changes

2024-02-23 06:38 UTC, merged