Remove warnings for K8s 1.31 and OCP 4.17.
dell/csi-powerstore pull request #352
Opened 2024-10-05 10:51 UTC by donatwork

# Description
Remove warnings from the script installer when on K8s 1.31 and OCP 4.17

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1472 |
| https://github.com/dell/csm/issues/1473 |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [X] Tested installer on K8s 1.31, no warnings about K8s 1.31
- [X] Tested installer on OCP 4.17, no warnings about OCP 4.17

2024-10-07 13:51 UTC, santhoshatdell approved these changes
Should we also update the min required version?

2024-10-07 13:58 UTC, lukeatdell commented
> Should we also update the min required version?

blame history shows k8s min version hasn't been updated in a while, but it looks like ocp is regularly updated.

2024-10-08 05:48 UTC, AkshaySainiDell requested changes

2024-10-08 05:48 UTC, AkshaySainiDell commented on dell-csi-helm-installer/verify-csi-powerstore.sh
> +  verify_openshift_versions "4.15" "4.17"
```suggestion
  verify_openshift_versions "4.16" "4.17"
```

2024-10-08 16:39 UTC, donatwork commented on dell-csi-helm-installer/verify-csi-powerstore.sh
> +  verify_openshift_versions "4.15" "4.17"
Done.

2024-10-08 16:40 UTC, donatwork commented
> Should we also update the min required version?

Min versions confirmed and updated.

2024-10-08 16:41 UTC, santhoshatdell approved these changes

2024-10-08 17:04 UTC, lukeatdell approved these changes

2024-10-08 17:15 UTC, merged