Updated code owners
dell/csi-powerstore pull request #39
Opened 2021-12-09 06:15 UTC by francis-nijay

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#128 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Testing not required as this is github code owners update

2021-12-09 06:17 UTC, bpjain2004 approved these changes

2021-12-09 06:18 UTC, harshitap26 approved these changes

2021-12-09 06:21 UTC, harishp8889 requested changes

2021-12-09 06:21 UTC, harishp8889 commented on .github/CODEOWNERS
> +# Pooja Prasannakumar (kumarp20)
Please arrange this in alphabetical order. Please see the comment in line 10

2021-12-09 06:36 UTC, prablr79 approved these changes

2021-12-15 08:28 UTC, harishp8889 approved these changes

2021-12-16 06:25 UTC, bpjain2004 approved these changes

2021-12-16 06:37 UTC, merged